### ISSUE TITLE
Add a component to playback historical telemetry data

### ISSUE THREAD

**Issue by seanlu99** [NASA-AMMOS/AIT-GUI#107]
A component that could playback historical telemetry data would be very useful. This component would display the time ranges that are available for each packet in the database, allow a query of data over a time range, and playback data from the query. There would also be a timeline that displays the timestamp location in the query. Sliding the knob on the timeline would change the timestamp location. There would also be buttons for play, pause, and abort. Aborting playback would return display back to realtime.

**Comment by leighgarbs** [comment]
Seems to at least partially overlap with #66
