### ISSUE TITLE
Config syntax error when launching ait-server

### ISSUE THREAD

**Issue by bruceplai** [NASA-AMMOS/AIT-GUI#133]
There is a config syntax error for ait-gui when launching ait-server, and ait-core and ait-gui are on master branch.  ait-gui issue-126 branch appears to work fine.

2019-08-27T10:21:50.961 | ERROR    | <type 'exceptions.SyntaxError'> creating plugin 0: invalid syntax (__init__.py, line 305)
2019-08-27T10:21:50.961 | WARNING  | No valid plugin configurations found. No plugins will be added.

Server plugins config:

        plugins:
            - plugin:
                name: ait.gui.AITGUIPlugin
                inputs:
                    - telem_stream
                    - log_stream
                outputs:
                    - command_stream

**Comment by robschneider16** [comment]
My bad. Thank you michael. My virtualenv was outdated so i never actually tested it 🥇
