### ISSUE TITLE
Datetime strptime format error

### ISSUE THREAD

**Issue by bruceplai** [NASA-AMMOS/AIT-GUI#140]
Datetime module strptime can only go up to microsecond precision when formatting datetime strings.  Possible solutions are to use a different module to handle datetime or truncate the string.

  File "/Users/blai/.virtualenvs/p2/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/blai/.virtualenvs/p2/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/blai/projects/ait-gui/ait/gui/__init__.py", line 1082, in handle
    dt = datetime.strptime(end_time, '%Y-%m-%dT%H:%M:%S.%fZ')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2019-10-08T22:41:48.120595869Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

**Comment by bruceplai** [comment]
Removing <ait-playback> tag from index.html also makes the issue go away, so there may need to be a fix done in the playback component.

**Comment by MJJoyce** [comment]
Note, line 1082 is the handler for the `/playback/range` route. The `strptime` format string is expecting milliseconds but getting more digits than that. Not sure specifically what in the playback component is passing this since I have dug in yet, but it's more that likely something in there.

**Comment by aywaldron** [comment]
Closing, duplicated in #143
