### ISSUE TITLE
Update dict.iteritems() (Py2) to dict.items() (Py3)

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-GUI#169]
We discovered at least one instance of the Python 2 dict's iteritems, which is no longer supported in Python 3:

https://github.com/NASA-AMMOS/AIT-GUI/blob/95594589d78501f547702e8bcca836616a852af2/ait/gui/__init__.py#L659

Update this instance and search for any others that missed testing.

**Comment by Futabay** [comment]
Thank you Nick I will!
