### ISSUE TITLE
GUI Plot seems to drop packets

### ISSUE THREAD

**Issue by Deepspace42** [NASA-AMMOS/AIT-GUI#24]
I'm sending packets (each 270 bytes) from a remote machine to another machine running AIT. When I plot the sequence count from the space packet header not all of the packets are plotted. I've verified with Wireshark that all of the packets are being sent and the AIT machine receives all of the packets. I also ran bliss-bsc and looking at the pcap file all of the packets are there. I've attached a picture of the plot, in this one there should be 32 packets. 

![screenshot from 2018-04-20 14-20-24](https://user-images.githubusercontent.com/5394032/39272287-81de0226-48a9-11e8-804b-44c86c1a57ed.png)

**Comment by MJJoyce** [comment]
Hey @Deepspace42,

The default refresh rate on the plots is once ever 10 seconds. Is it possible that you just need to wait a few seconds for the plot to refresh again? You can try setting `redraw-frequency=1` on the `bliss-plot` tag to up the refresh rate to see if this is the case.

**Comment by Deepspace42** [comment]
Thansk @MJJoyce,

That resolved the issue. Where could I look for further options like redraw-frequency?

**Comment by MJJoyce** [comment]
Hey @Deepspace42,

Unfortunately there's not a place to easily check out those options. It's one of the outstanding todos for fleshing out the GUI docs. 

You can look at the [plotting code](https://github.com/NASA-AMMOS/AIT-GUI/blob/master/bliss/gui/static/js/bliss/gui/Plot.js#L317) for some of the specific settings. I've copied most of the related ones below with a brief explanation. I realize digging through code isn't convenient, so in the interim keep the questions coming on our [dev/users google group](https://groups.google.com/forum/#!forum/ait-dev) or here. It'll keep us motivated to get those updates out 😀 

Just a note, you shouldn't need these for a simple use-case. This is primarily to help with large numbers of plots refreshing all at the same time and causing performance problems.
```
# If true, enable semi-random redraw frequency variation for the plot. This
# adds a random amount of variation to the redraw-frequency for the plot
# such that the redraw time will be redraw-frequency + [redraw-frequency-variation-min, *-max]
redraw-frequency-variation

# Set the min variation for the above
redraw-frequency-variation-min
# Set the max variation for the above
redraw-frequency-variation-max
```

**Comment by MJJoyce** [comment]
I'm closing this as not an issue. If you run into any other problems please send us a message on our user group or open another ticket. Thanks!
